version: '3.9'
services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api_development
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものにする
    cap_add:
      - SYS_NICE # mbind: Operation not permitted のエラーを直す

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - ./api:/myapp/api
    ports:
      - "3001:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - EDITOR=vim

volumes:
  mysql_data: