export const SITE_FULL_NAME = "サイトタイトル"
export const SITE_NAME_KANA = "サイトタイトル"
export const SITE_NAME = "サイトタイトル"
export const SITE_DOMAIN = "https://hoge.net"
export const SITE_DESCRIPTION = "サイトのデスクリプション"